#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# Thêm PATH chứa npx
export PATH=$PATH:/usr/local/bin

# Disable concurrent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.." && npx lint-staged --concurrent false